### ISSUE TITLE
Seg fault when connecting

### ISSUE THREAD

**Issue by jcward** [jcward/hxScout#53]
Linux, saw seg fault when AUT connecting:

[Switching to Thread 0x7fffdebf1700 (LWP 28523)]
0x00000000005eae2d in FLMListener_obj::start() ()
(gdb) bt
#0  0x00000000005eae2d in FLMListener_obj::start() ()
#1  0x00000000005ece59 in __FLMListener_objstart() ()
#2  0x0000000000682ce7 in hx::CStaticFunction0::__run() ()
#3  0x000000000066f6f8 in hxThreadFunc(void*) ()
#4  0x00007ffff7bc4182 in start_thread (arg=0x7fffdebf1700) at pthread_create.c:312
#5  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread apply all bt

Thread 9 (Thread 0x7fffde3f0700 (LWP 28635)):
#0  0x00007ffff7bcb6dd in accept () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff409388e in socket_accept(_value*) () from ./std.dso
#2  0x0000000000662a70 in ExternalPrimitive::__run(Dynamic const&) ()
#3  0x0000000000425f72 in sys::net::Socket_obj::accept() ()
#4  0x00000000005ea6a5 in FLMListener_obj::start() ()
#5  0x00000000005ece59 in __FLMListener_objstart() ()
#6  0x0000000000682ce7 in hx::CStaticFunction0::__run() ()
#7  0x000000000066f6f8 in hxThreadFunc(void*) ()
#8  0x00007ffff7bc4182 in start_thread (arg=0x7fffde3f0700) at pthread_create.c:312
#9  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 8 (Thread 0x7fffdebf1700 (LWP 28523)):
#0  0x00000000005eae2d in FLMListener_obj::start() ()
#1  0x00000000005ece59 in __FLMListener_objstart() ()
#2  0x0000000000682ce7 in hx::CStaticFunction0::__run() ()
#3  0x000000000066f6f8 in hxThreadFunc(void*) ()
#4  0x00007ffff7bc4182 in start_thread (arg=0x7fffdebf1700) at pthread_create.c:312
#5  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 7 (Thread 0x7fffdf5fe700 (LWP 28522)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000006706cb in __hxcpp_thread_read_message(bool) ()
#2  0x000000000058ddbd in cpp::vm::Thread_obj::readMessage(bool) ()
#3  0x0000000000572485 in hxtelemetry::HxTelemetry_obj::start_writer() ()
#4  0x00000000005726a9 in hxtelemetry::__HxTelemetry_objstart_writer() ()
#5  0x0000000000682ce7 in hx::CStaticFunction0::__run() ()
---Type <return> to continue, or q <return> to quit---
#6  0x000000000066f6f8 in hxThreadFunc(void*) ()
#7  0x00007ffff7bc4182 in start_thread (arg=0x7fffdf5fe700) at pthread_create.c:312
#8  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7fffdffff700 (LWP 28521)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x00007ffff47d542e in SDL_SemWait_REAL () from ././lime-legacy.ndll
#2  0x00007ffff47d5585 in SDL_SemWaitTimeout_REAL () from ././lime-legacy.ndll
#3  0x00007ffff47843b1 in SDL_TimerThread () from ././lime-legacy.ndll
#4  0x00007ffff4783f4d in SDL_RunThread () from ././lime-legacy.ndll
#5  0x00007ffff47d5629 in RunThread () from ././lime-legacy.ndll
#6  0x00007ffff7bc4182 in start_thread (arg=0x7fffdffff700) at pthread_create.c:312
#7  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7ffff55ce700 (LWP 28520)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000648abb in GlobalAllocator::SMarkerFunc(void*) ()
#2  0x00007ffff7bc4182 in start_thread (arg=0x7ffff55ce700) at pthread_create.c:312
#3  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7ffff5dcf700 (LWP 28519)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000648abb in GlobalAllocator::SMarkerFunc(void*) ()
#2  0x00007ffff7bc4182 in start_thread (arg=0x7ffff5dcf700) at pthread_create.c:312
#3  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7ffff65d0700 (LWP 28518)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
---Type <return> to continue, or q <return> to quit---
#1  0x0000000000648abb in GlobalAllocator::SMarkerFunc(void*) ()
#2  0x00007ffff7bc4182 in start_thread (arg=0x7ffff65d0700) at pthread_create.c:312
#3  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7ffff6dd1700 (LWP 28517)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000648abb in GlobalAllocator::SMarkerFunc(void*) ()
#2  0x00007ffff7bc4182 in start_thread (arg=0x7ffff6dd1700) at pthread_create.c:312
#3  0x00007ffff6eccfbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7ffff7fce780 (LWP 28513)):
#0  0x000000000065ded4 in hx::Hash<hx::TStringElement<Dynamic> >::expandBuckets(int) ()
#1  0x000000000065eeec in hx::Hash<hx::TStringElement<Dynamic> >::set(String, Dynamic const&) ()
#2  0x000000000064c316 in __string_hash_set(Dynamic&, String, Dynamic const&, bool) ()
#3  0x000000000063f77e in hx::Anon_obj::__SetField(String const&, Dynamic const&, hx::PropertyAccessMode) ()
#4  0x0000000000640fd5 in alloc_field ()
#5  0x00007ffff456062d in external_handler(nme::Event&, void*) () from ././lime-legacy.ndll
#6  0x00007ffff454b724 in nme::Stage::HandleEvent(nme::Event&) () from ././lime-legacy.ndll
#7  0x00007ffff450e62f in nme::StartAnimation() () from ././lime-legacy.ndll
#8  0x00007ffff450ebd0 in nme::CreateMainFrame(void (*)(nme::Frame*), int, int, unsigned int, char const*, nme::Surface*) ()
   from ././lime-legacy.ndll
#9  0x00007ffff45689e3 in nme_create_main_frame(_value**, int) () from ././lime-legacy.ndll
#10 0x00000000006631a6 in ExternalPrimitive::__Run(Array<Dynamic> const&) ()
#11 0x000000000067ef27 in Dynamic::operator()(Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&) ()
#12 0x000000000062dc72 in openfl::_legacy::Lib_obj::create(Dynamic, int, int, hx::Null<double>, hx::Null<int>, hx::Null<int>, String, hx::ObjectPtr<openfl::_legacy::display::BitmapData_obj>, hx::ObjectPtr<hx::Class_obj>) ()
#13 0x000000000042376c in ApplicationMain_obj::main() ()
---Type <return> to continue, or q <return> to quit---
#14 0x0000000000423a99 in main ()
(gdb) quit

**Comment by jcward** [comment]
Haven't seen this recently.
